# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(related_name='posts', to='blog.Comment'),
        ),
    ]
